### ISSUE TITLE
Why has noone built any rpms for this for EPEL 9 yet?

### ISSUE THREAD

**Issue by SupremeGit** [vmware/pyvmomi#1023]
### Describe the bug

Its being built for epel 7, epel 8, fedora 37, 38, rawhide, but not epel 9
eg here:
https://koschei.fedoraproject.org/package/python-pyvmomi?collection=epel8

Why has noone anywhere in the entire world built any rpms for this for EL 9 yet?

### Reproduction steps

1. try to get rpms for el9 from epel 9 or anywhere else.
2. FAIL MISERABLY
3.
...

### Expected behavior

rpms available for el9.
expecting people to use pip on el9 is nonsense, rpms are needed.

### Additional context

thanks in advance.

**Comment by DanielDraganov** [comment]
Hello,
Although we wish to have more distribution channels for pyVmomi there is so much that we could handle and manage on our side.
I'm not aware of RPM, deb or other packages to have been ever produced by the pyVmomi maintainers.
As those could be distribution specific, it is up to the related community to produce and maintain those packages.

Based on the above info, this issue is closed. Note is taken and we will consider the Fedora community if we expand our package distribution.
