### ISSUE TITLE
No verification of server certificates

### ISSUE THREAD

**Issue by ericwb** [vmware/pyvmomi#13]
Pyvmomi uses httplib and urllib which do no do any certificate verification.  But most products do prefer to have some control of how host certificates are verified in order to avoid man-in-the-middle attacks.

Probably the easiest way to get this supported properly is to switch from httplib to python requests - http://docs.python-requests.org/en/latest/

**Comment by jantman** [comment]
Just as a comment, if certificate verification is added, please make sure there's an option to disable it.

**Comment by pontillo** [comment]
Actually, I would argue that (in order to maintain compatibility with previous versions) verification should be disabled by default. (not because I think not verifying certificates is a good idea in general, but because it would break API compatibility with previous revisions... and I expect that many people would not bother to configure trusted certificates for this purpose, since pyvmomi will usually be run on what amounts to a relatively trusted network.)

**Comment by hartsock** [comment]
I'll try and do a pull request for this shortly. My instinct is to add option flags to go with default = disabled through out the API. But, do something clever so that when in a "production" class environment we trip something and fall into enabled. Maybe a magic local environment variable for development?

We can discuss it in the pull request.

**Comment by pcn** [comment]
I really think that a default option is the right way to go - eliminating surprise.  Sites/individuals can wrap that and make their own determination as to whether they want a prod/dev split in how certs are treated.  In most ops situations your sysadmins will be much happier if dev/stage/qa/test/ci/production all have the same behavior and the same flags enabled.

**Comment by hartsock** [comment]
@pcn okay, we'll go with *easy* first.

**Comment by hartsock** [comment]
Note: see https://github.com/vmware/pyvmomi/pull/252 and https://github.com/vmware/pyvmomi/issues/212 which are related to this issue.

**Comment by tianhao64** [comment]
The httplib has already been replaced by request. Thx @michaelrice .Since change https://github.com/vmware/pyvmomi/commit/92c1de5056be7c5390ac2a28eb08ad939a4b7cdd, ssoContext can be passed to Connect and SmartConnect to disable the certificate verification.
