### ISSUE TITLE
support for vSphere 6.0?

### ISSUE THREAD

**Issue by strongliang** [vmware/pyvmomi#209]
vSphere 6.0 is released today ([what's new](https://www.vmware.com/files/pdf/vsphere/VMware-vSphere-Whats-New.pdf)).

will pyVmomi support it, and if so, when's the planned release?

**Comment by hartsock** [comment]
There will be a version of `pyVmomi` that ships inside the vSphere 6.0 release that will have support for all the public API. We will be able to port the new features after that version is publicly available. Since the new version is not yet available for download, we will have to wait on that and put the new API into our code-base for the upgrade cycle. I am *informally* planning on 2 releases in 2015 but I'm not ready to declare a timeline at this time. I anticipate a release in Q2 of 2015 and a release in Q3 of 2015.

I just started work on the next release Thursday and will mark milestones here when we get firmer plans for the rest of Q1 and Q2 of 2015.
