### ISSUE TITLE
Serialize to JSON?

### ISSUE THREAD

**Issue by dnaeon** [vmware/pyvmomi#21]
Hi,

I was wondering whether it is possible to serialize an object properties to JSON?

For example taking the following code snippet, how could I dump the `vm.summary` properties to JSON?

```
>>> from pyVim.connect import SmartConnect, Disconnect
>>> si = SmartConnect(host='vc01', user='root', pwd='password')
>>> datacenter = content.rootFolder.childEntity[0]
>>> vmFolder = datacenter.vmFolder
>>> vmList = vmFolder.childEntity
>>> vm = vmList[1].childEntity[1]
>>> vm
'vim.VirtualMachine:vm-182'
>>> vm.summary
```

Having a JSON serializer would really make things simple and easier to integrate with other systems. 

Is this possible using pyVmomi?

Thanks and regards,
Marin

**Comment by leroux** [comment]
+1

**Comment by paul-mulvihill** [comment]
+1

**Comment by cybervedaa** [comment]
+1

**Comment by kulkarnisu** [comment]
+1

**Comment by Akasurde** [comment]
+1

**Comment by copdips** [comment]
+1 , got pickle error during multiprocessing due to pyvmomi object not picklable

**Comment by hartsock** [comment]
Hi, @tianhao64 any progress on this?

**Comment by ilmarh** [comment]
i've derived dict() convertion from pyVmomi.Support.Format(). Checked on Event objects, maybe somebody will use it.
https://github.com/ilmarh/vmevent2dict

**Comment by hartsock** [comment]
@tianhao64 what do you think?

**Comment by tianhao64** [comment]
Hi @hartsock , I am not currently working on this. I'd encourage the community to contribute and implement this enhancement.

**Comment by jeking3** [comment]
I submitted a pull request into the ansible `vmware_guest_facts` module that allows for transformation to JSON.  If folks are interested I can pull it in here.

https://github.com/ansible/ansible/pull/47446

**Comment by jeking3** [comment]
I'm working on pulling this in.

**Comment by hartsock** [comment]
@jeking3  thanks!

**Comment by jeking3** [comment]
I have it mostly working along with vcr tests for VirtualMachine and for HostSystem types.  One of the unfortunately gotchas with python 2/3 support is that in python2 a six.binary_type is a `str` and in python3 it is a `bytes`.  Since it is a `str` in python2, the base encoder tries to convert the type because it believes the value is a basic type, and never comes back up to the default method in the custom encoder.  I think it's reasonable to say that the internal representation of a checksum as a string with high-bit characters in it is incorrect.  In python2 a binary should be a byte[] and not a str.

**Comment by jeking3** [comment]
I changed the internal representation of a binary from `six.binary_type` to `bytearray` for python2.  It'll be in the PR, once you have a chance to digest it we can discuss the implications.

**Comment by hartsock** [comment]
@tianhao64 is the one who's responsible for this project now, so make sure to "at" him when you're ready.

I also think we may have a policy of asking for contributors to sign something now. Tian will know.
