### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by crichon** [vmware/pyvmomi#210]
Hi

I didn't spend much time checking it, but at least,

https://github.com/vmware/pyvmomi/blob/master/docs/vim/VirtualMachine.rst

is not up to date. Method **ReconfigVm** does not exist. Actually, it's **ReconfigVM_Task** or **Reconfigure**. Both seem to work.

Could you please check and update the documentation ? Thanks

**Comment by crichon** [comment]
Sorry I posted before checking opened issues. This one relate to #181, so I am closing it.

**Comment by hartsock** [comment]
@crichon thanks... and *yes* we currently *have* documentation but it could be *a lot* better. I need volunteers inside VMware to help with that because of how the docs get made. Ideally we should be able to produce [something like this](http://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.wssdk.apiref.doc/index-mo_types.html) (note the search feature) but for Ruby and Python specifically.

Do comment on the parent bug. We're ramping up for 2015 again and I hope to start seeing some forward velocity on the project soon as we on board new contributors.
