### ISSUE TITLE
what's the relationship between pyVmomi and the vCloud Python SDK?

### ISSUE THREAD

**Issue by strongliang** [vmware/pyvmomi#217]
I just realized that there is a Python SDK included in the vSphere 6 release but it looks quite a bit different from pyVmomi.

**Comment by hartsock** [comment]
I'm actually in the process of discussing this with various project owners. This project is a [VMware Labs fling](https://labs.vmware.com/about) and does not fall under the normal support and release cycle umbrella. We release asynchronously and we're not under the same constraints as other projects (we're under different constraints in resources, legality, and process).

At the moment there is no relationship at all between the two SDK. No one on this project was consulted in any way on the development of any other SDK that VMware is presently releasing. We have no meaningful input into that process at all. That said, I would *like* to pursue as *seamless* a developer experience between the various SDK as possible.

It would be beneficial for us to determine the best way to do this with the least effort from either party. As a personal aspirational statement, I would like to see this manner of development (as seen on pyVmomi) become the de facto standard method for VMware to pursue enhancement and development of SDK. This is a naturally controversial statement and may not reflect the larger considerations that VMware as a corporate entity may choose to pursue.

As a general rule, because of this projects status within the VMware ecosystem you can expect it to lag the official release cycle by roughly 6 months and experience a quiet period during Q4 and Q1 of each year... some quiet periods just ahead of and just after official releases... and then hopefully a flurry of activity after we hear experimental API and changes are now ready for public consumption.

**Comment by hartsock** [comment]
This response was a little difficult for me to write and I'm sorry for any confusion it may cause.
