### ISSUE TITLE
vSphere 6 support.

### ISSUE THREAD

**Issue by Udayan12167** [vmware/pyvmomi#231]
I would like to use pyvmomi with vsphere 6 but it only supports till api version 5.5 when is a version for 6 coming out?

**Comment by hartsock** [comment]
At the moment I'm working on this on a volunteer basis so it's best effort. I was hoping for 2 releases this year with the second release containing 6.0 support. The second release I was hoping to be able to assemble by the end of July 2015... but I can't control my velocity because I can't tell when other projects are going to require my attention.

**Comment by Udayan12167** [comment]
Is it possible to run pyVmomi 5.5 with esx6?

**Comment by michaelrice** [comment]
@Udayan12167  I have not tested it but it should work fine. You wouldnt be able to use any of the new 6.0 MO or methods or properties, but it should be backwards compatible.

**Comment by michaelrice** [comment]
@hartsock Is it possible to get the tool that creates ServerObjects.py open sourced?Or even to have it published as closed source by VMWare?

**Comment by strongliang** [comment]
I tested a VM backup app written with v5.5 on a VM on ESX6 and it worked. So at least it works to some extent.

**Comment by Udayan12167** [comment]
Hey Thank you guys i think this solves my problem. :)

**Comment by hartsock** [comment]
@michaelrice I will ask around again, but it was rather unlikely last time.

**Comment by michaelrice** [comment]
@hartsock I think with out it, it makes this vsphere 6 support issue hard to add the "help wanted" tag to because it means someone has to hand edit that server objects file which could end up being problem ridden because of the syntax. I guess some of that could be handled with tests, but the tool would be most ideal. Ill cross my fingers and hope for the best. :four_leaf_clover:

**Comment by strongliang** [comment]
any update on this?

**Comment by hartsock** [comment]
@strongliang we are still looking for support from VMware employees. Most folks are very busy right now and we're not able to get the free time we need to finish this part.

**Comment by ningke** [comment]
@hartsock What exactly involved in porting to vSphere 6? A few weeks ago when I needed a vSphere6 only DataObject (VirtualVideoCard.graphicsMemorySizeInKB), I ended up "hacking" in the new field in ServerObjects. I still would like add a few more functionalities that I don't want to keep hacking. If someone knows the exact process to port, I might be able to help.

**Comment by michaelrice** [comment]
@ningke that is the process.. you have to add all the new dataobject, faults, enums, managed objects, then update all the existing with new properties, then you also have to add the proper vim namespace so that it wouldnt have to be manually set in the connection.. Its a tedious process.

**Comment by ningke** [comment]
@michaelrice Could we auto-generate the Data and Managed Object definition in ServerObjects.py by translating some kind of VMODL XML spec?

**Comment by michaelrice** [comment]
@ningke https://github.com/vmware/pyvmomi/issues/231#issuecomment-88180170

VMWare has a tool that does it already.

**Comment by ningke** [comment]
@michaelrice Cool. I am a VMware employee btw:)

**Comment by michaelrice** [comment]
@ningke Awesome. Join forces with @hartsock and apply fierce amounts of peer pressure and get that tool open sourced ;)

**Comment by grzn** [comment]
VMware has several forks of pyVmomi, and the one inside the VCSA has all the VC6.0 data and managed objects (along with some internal data objects that were not included in this open-source branch until now).

Looking at the diff between VCSA5.5u2 and VCSA6.0, it shouldn't take much work to update the data objects. Its a shame that VMware has the tools to generate these files (and has them inside VSA), and yet chooses to keep Python community behind.

BTW, I had a [long discussion](https://github.com/vmware/pyvmomi/issues/35) about releasing the entire APIs to open-source (or at least the marshalling part) with @hartsock  back at September, but nothing changed since.

**Comment by hartsock** [comment]
Hey folks. I'm currently heads down on a critical path of a different project so I've not had much time to donate to pyVmomi. I'm expecting to start seeing work from @parthgala to address these concerns as he's coming up to speed on the project.

**Comment by jcpowermac** [comment]
As a VMware customer how would I add "fuel to the fire" to get this better supported within VMware?  I am fairly concerned at the current development of this project and our use of this for our Ansible modules.

**Comment by michaelrice** [comment]
@jcpowermac If you have a TAM let them know how important this is to you, otherwise just use your normal AM.

**Comment by twarnock** [comment]
I am reaching out to my contacts in VMware to escalate this, but wanted to throw in my support here for getting this issue resolved.

**Comment by grzn** [comment]
@michaelrice any progress wit this one?

**Comment by grzn** [comment]
@parthgala do you have any update for us on this?

**Comment by codekoala** [comment]
I'm eagerly awaiting this, as a major effort at work requires the new IO filter features. Any change?

**Comment by hartsock** [comment]
cc @tianhao64

**Comment by divad** [comment]
Is there any chance of an update on pyvmomi supporting vCenter 6?

**Comment by hartsock** [comment]
Attn: @tianhao64 && @parthgala

**Comment by tianhao64** [comment]
v6.0.0 is just released: https://github.com/vmware/pyvmomi/releases/tag/v6.0.0

**Comment by codekoala** [comment]
Excellent, thanks! I'll try it when I get to work tomorrow :)

**Comment by tianhao64** [comment]
Sorry about the delay. Thank you everyone for your patience! Please let us know if you see any regression issues. 

Regards,
Tianhao

**Comment by aryaanand** [comment]
I am trying to deploy ovf on vCenter 6. I think still the vim version is not supported for vCenter 6. Any update on this ? This is the issue I faced 
https://github.com/vmware/pyvmomi/issues/322
