### ISSUE TITLE
Snapshot storage size

### ISSUE THREAD

**Issue by jm66** [vmware/pyvmomi#241]
Hi,

I've been trying to get the used storage of each snapshot taken in certain VM, however, I haven't had much success on this. So far, I cannot find where are the 'delta' disks and because of this missing piece, the Snapshot size (memory + delta disks) is not as accurate as presented in the vSphere web client :

`vm.snapshot` > provides snapshots on this VM
`vm.layout.snapshot`  > provides relationship snapshot id - > disk name
`vm.layoutEx.snapshot` > provides relationship snapshot id - > disks id
`vm.layoutEx.file` > provides size for each file

Have you guys ever done this?

Thanks,
JM

**Comment by stemid** [comment]
Here's a response from user whereismyjetpack on #pyvmomi@freenode.

    def get_snapshot_size(vsphere_vm):
        """returns snapshot size, in GB for a VM"""
        disk_list = vsphere_vm.layoutEx.file
        size = 0
        for disk in disk_list:
            if disk.type == 'snapshotData':
                size += disk.size
            ss_disk = re.search('0000\d\d', disk.name)
            if ss_disk:
                size += disk.size

        size_gb = (float(size) / 1024 / 1024 / 1024)
        return round(size_gb, 2)

This code helped me figure it out at least, it goes by disk.type being 'snapshotData' but then it also checks the disk filename for the pattern 0000## because those files are snapshots. 

This is less secure than the PowerCLI API where you have Snapshot.SizeGB but it works for now.
