### ISSUE TITLE
vim.TaskInfo.State returns Success for pyvmomi clone before the action completes on vcenter

### ISSUE THREAD

**Issue by rashrag** [vmware/pyvmomi#288]
Hi,
I am trying to clone a vm to a template. But before the clone has fully succeeded on the vcenter, the vm.TaskInfo.State changes from running to success.

**Comment by parthgala** [comment]
Hi,
How did you determine that the operation wasn't completed on vCenter?
Thanks !

**Comment by rashrag** [comment]
Hi,
I was able to observe on the vsphere client that the clone task was only
40% complete. However I was printing the info state and it was success.
Previous to starting the cloning, I was powering off the vm.

**Comment by rreubenur** [comment]
I don't know the root cause of this problem. But I replaced my wait_for_tasks() method with the one provided in the community.

In my previous code I was only checking ```vim.TaskInfo.State``` . But it was erroneous. Then I used the community code which is using ```PropertyCollector``` and Filters.  This code is reliable and working perfectly fine.

You can give a try. Only experts can tell you the root cause or a specific solution.

**Comment by rashrag** [comment]
Thank you! Will check it out!
