### ISSUE TITLE
Add support for Support for esxcli like the Ruby bindings

### ISSUE THREAD

**Issue by grzn** [vmware/pyvmomi#34]

**Comment by hartsock** [comment]
@wiggin15 good points. We may be forced to avoid supporting ESXCLI in the main library. One possible work-around is to allow for pyVmomi "plugins" that could support unofficial API inside themselves. I'll investigate further before release time.

**Comment by rameshsangepu** [comment]
I understand this quite old post but I just came across a need to query esx vibs through python. Is 'esxcli' part of pyvmomi ?

**Comment by hartsock** [comment]
@rameshsangepu if I'm not mistaken @tianhao64 is directing folks this direction https://code.vmware.com/web/sdk/67/vsphere-automation-python

**Comment by wiggin15** [comment]
@rameshsangepu FYI, if you need esxcli support in the meantime until it is added to pyvmomi, we have support for that in our wrapper, infi.pyvmomi_wrapper: 

https://github.com/Infinidat/infi.pyvmomi_wrapper
https://github.com/Infinidat/infi.pyvmomi_wrapper/tree/develop/src/infi/pyvmomi_wrapper/esxcli

**Comment by alv000h** [comment]
+1 for esxcli support in pyvmomi
@hartsock @tianhao64 Why was this issue closed?

**Comment by hartsock** [comment]
@alv000h the short answer is that there is a wrapper to work around this issue. That's why I closed this. @tianhao64 has moved off the project and @pgbidkar is driving development at VMware for this now. Since I'm not in a position to advocate for this change with those groups I'd have to defer to @pgbidkar and ask if he thinks he should reopen this and if the core development team would look at adding this feature.

**Comment by csdozier** [comment]
I found the esxcli implementation in the wrapper to be incomplete.   +1 for complete esxcli support in pyvmomi

**Comment by markuszeiter** [comment]
@pgbidkar are there any plans that the core team would add this feature to pyvmomi?
