### ISSUE TITLE
Add support for the Sms APIs

### ISSUE THREAD

**Issue by grzn** [vmware/pyvmomi#35]

**Comment by hartsock** [comment]
@cameronsparr I'm assigned to a new project right now and I'm on a critical path so I've not had much time the last few months to donate to pyVmomi. I am expecting @parthgala to start making contributions in these directions as he's coming up to speed on the project.

**Comment by tianhao64** [comment]
Sms api type is uploaded. Feel free to give it a try and report any issues. Thank you!

**Comment by wiggin15** [comment]
Hi @tianhao64, thank you very much for the inclusion of the SMS API in pyvmomi.
To use the SMS API using sms.ServiceInstance, the user must instantiate the class with a SoapStubAdapter. It is mandatory that this adapter send an additional SOAP header named vcSessionCookie for authentication.
It is currently trivial to pass this SOAP header and not possible to do that without affecting all stub adapters in the thread: the code that adds SOAP headers is in https://github.com/vmware/pyvmomi/blob/master/pyVmomi/SoapAdapter.py#L874, and from here we can see that the user must change `_threadLocalContext['reqCtx']`. This is not good because it requires changing an internal global variable and also affects the thread context, which means that the regular clients are affected to.
Please see the discussion and commit in https://github.com/vmware/pyvmomi/pull/165.

**Comment by tianhao64** [comment]
Hi @wiggin15 , I will forward your message and proposed changes to my team and try to get back to you probably next week.

**Comment by wiggin15** [comment]
@tianhao64 is there an update?
