### ISSUE TITLE
Cross-vcenter template clone (enhanced linked mode)

### ISSUE THREAD

**Issue by Retenodus** [vmware/pyvmomi#490]
Hello,

I recently migrated to Vsphere 6 and I see that with the "Enhanced Linked Mode" feature, we can do cross-vcenter template clone.

Does anyone have an idea how to achieve that ? Is the API for Enhanced Linked mode exposed ? I get hints that it could be as the RelocateSpec documentation says that “If the virtual machine is relocated to a different vCenter service, both the destination host and resource pool have to be specified and cannot be unset.” Does that mean we can just specify a HostSystem which belongs to another Service Instance ? Or do we have to use SSO ?

Thank you,
Regards,
Grégoire

**Comment by prziborowski** [comment]
Hello,
I haven't ever tried cross-vcenter clone of a template, so perhaps you'll be my guinea pig.

To do cross-vc, you just need to populate the service part of the RelocateSpec's service ( http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.ServiceLocator.html).
If your vCenter Servers are not linked, then you will have to provide the sslThumbprint.
Otherwise the instanceUuid, url, and credential are needed.
credential can be a username/password combination. Otherwise using SSO you'd provide the SAML token.
The vcenter's uuid is available from the ServiceInstanceContent.about.instanceUuid.
The url is likely https://$host:443/sdk

You will have to provide all the destination information (resource pool, folder, datastore, host) as they are unique to each vCenter Server.

**Comment by Retenodus** [comment]
Hello,

Indeed, it worked :)

I can confirm that url was "https://$host:443/sdk"

For information, I used something like that :

```python
service_locator = vim.ServiceLocator()
service_locator.instanceUuid = destination_vcenter_si.content.about.instanceUuid
service_locator.url = url
service_locator.sslThumbprint = sslThumbprint
creds = vim.ServiceLocatorNamePassword()
creds.username = user
creds.password = pwd
service_locator.credential = creds

relocatespec = vim.vm.RelocateSpec()
relocatespec.datastore = destination_datastore
relocatespec.pool = destination_resource_pool
relocatespec.service = service_locator

container = destination_vcenter_si.content.viewManager.CreateContainerView(destination_vcenter_si.content.rootFolder, [vim.HostSystem], True)
for c in container2.view:
	if c.name == ESXI_NAME:
		hostsystem = c

relocatespec.host = hostsystem

configspec = vim.vm.ConfigSpec()
configspec.numCPUs = 1
configspec.memoryMB = 1024

clonespec = vim.vm.CloneSpec()
clonespec.config = configspec
clonespec.powerOn = False
clonespec.location = relocatespec

task = template.CloneVM_Task(folder=destfolder, name=name, spec=clonespec)
```

I did not include all the initialization part, but template must be a template on origin vcenter whereas all other information must be valid on the destination vcenter.

Regards,
Grégoire
