### ISSUE TITLE
Update virtual disk on vm while cloning from template

### ISSUE THREAD

**Issue by murarisumit** [vmware/pyvmomi#558]
I'm able to do this with GUI, can increase the disk size while cloning the template. 
How can I do it via pyvmomi ?

**Comment by prziborowski** [comment]
It is recommended to do a reconfigure post-clone to make changes to the clone.
It could be similar to [change_disk_mode.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/change_disk_mode.py), but rather than changing the disk mode,
```    virtual_disk_spec.device.capacityInBytes = newSize```

There is a deprecated way by passing it in the [CloneSpec](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.CloneSpec.html).config
You would need to pass in the virtual disk and change the capacity to a higher value (but this becomes more complicated because it could change other values unexpectedly, such as file name paths).

**Comment by murarisumit** [comment]
@prziborowski thanks for the answer again, will test it up and close the ticket.

**Comment by murarisumit** [comment]
@prziborowski it works, example was of great help.
