### ISSUE TITLE
How to set Entity Permissions on a Resource Pool

### ISSUE THREAD

**Issue by yyefet** [vmware/pyvmomi#608]
How can I use Pyvmomi to SET permissions (ie: add Active Directory Group) on a newly created Resource Pool.

I stumbled upon vim.AuthorizationManager.Permission but I don't see any methods to 'Add Permission to Entity'...  

Can anyone point me in the right direction?

Thanks in advance.

**Comment by prziborowski** [comment]
In the [AuthorizationManager](https://code.vmware.com/apis/196/vsphere#/doc/vim.AuthorizationManager.html) (accessible from ServiceInstance.content.authorizationManager) try using [SetEntityPermissions](https://code.vmware.com/apis/196/vsphere#/doc/vim.AuthorizationManager.html#setEntityPermissions) method. I believe that will add them. ResetEntityPermissions would replace them, and RemoveEntityPermission would remove the specified ones.
You can call RetrieveAllPermissions to see what is available to use (it returns a list of Permission).

**Comment by yyefet** [comment]
Awesome, that is exactly what I am looking for...
Follow up question...

How can I create a vim.AuthorizationManager.Permission object from scratch?

**Comment by prziborowski** [comment]
```
from pyVmomi import vim
...
perm = vim.AuthorizationManager.Permission()
perm.entity = rp # managed object for the resource pool you created
perm.group = False
perm.user = 'user@vsphere.local' # actual user name and group.
perm.propagate = True
perm.roleId = 12345 # whichever number the roleId actually is.
```
or
```
perm = vim.AuthorizationManager.Permission(
   entity=rp,
   group=False,
   user='user@vsphere.local',
   propagate=True,
   roleId=12345)
```

**Comment by gtomsho** [comment]
I realize this thread is old, but I am having trouble calling the SetEntityPermissions() method to set a permission on a VM. Here is what I'm doing:
vm_mo = vim.VirtualMachine("VMName")
perm = vim.AuthorizationManager.Permission( filled in similar to above)

vim.AuthorizationManager.SetEntityPermissions(vm_mo,[perm])

This generates an error: For entity expected type vim.ManagedEntity, but got list.
Can someone demonstrate how to correctly call the SetEntityPermissions() method?

Thank you,
Greg Tomsho

**Comment by prziborowski** [comment]
> I realize this thread is old, but I am having trouble calling the SetEntityPermissions() method to set a permission on a VM. Here is what I'm doing:
> vm_mo = vim.VirtualMachine("VMName")
> perm = vim.AuthorizationManager.Permission( filled in similar to above)
> 
> vim.AuthorizationManager.SetEntityPermissions(vm_mo,[perm])
> 
> This generates an error: For entity expected type vim.ManagedEntity, but got list.
> Can someone demonstrate how to correctly call the SetEntityPermissions() method?
> 
> Thank you,
> Greg Tomsho

I guess there is a lot to comment on.
There are 2 kinds of objects: DataObjects and ManagedObjects. VirtualMachine and AuthorizationManager are ManagedObjects, and AuthorizationManager.Permission is a DataObject. You can fill out the DataObjects yourself, but for ManagedObjects, it is best to fetch them from the server.

So if you connected with something like `si = SmartConnectNoSSL(...)` then you can fetch the AuthorizationManager with `authMgr = si.content.authorizationManager`
As far as fetching the VM by name there is an example here: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/soft_reboot.py#L23

Now you should be able to do:
`authMgr.SetEntityPermissions(vm_mo,[perm])`

The difference this is from your example is authMgr is an instance of the AuthorizationManager class, while what you were doing is trying to call a method of the class. But pyVmomi stores a lots of internal details in the instance in order to execute the methods (endpoint, cookie, moId).

**Comment by gtomsho** [comment]
@prziborowski: Thank you so much for your response. After a little fiddling with the getting-VM-by-name part, I was able to set permissions on the VM. I am a big fan of reading the documentation to learn how to do these types of things but I cannot find a definitive source that would have helped me with this. Do you know of some documentation that could have enlightened me on how to do this? The two biggest hurdles were assigning an instance of authMgr and getting the VM MO reference. 
In any case, I really appreciate your quick response and setting me on the right course.
Regards,
Greg

**Comment by prziborowski** [comment]
I wish I had a document to share for this. For looking up the APIs and the inputs/outputs I rely on https://code.vmware.com/apis/968/vsphere and the guide https://code.vmware.com/docs/1132/vsphere-web-services-sdk-programming-guide/doc/PG_Programming_Model.4.4.html but as far as how to use the pyVmomi bindings I am not aware of a good guide. I just learned it over many years of usage.

**Comment by gtomsho** [comment]
@ prziborowski:

 

You have been very helpful and I really appreciate your time. If you have time to answer another question, if not, I fully understand, your time is valuable:

 

So, this is the end goal: I’m using Flask to build a Python-based Web front-end to vCenter which is the basis for our cyberrange (I am a program director for cybersecurity at a Community College). Cyberrange users will create a user account, pick a cyberrange challenge, and then get access to one or more VMs (which is why I needed to know how to assign permissions). I could simply log them on to vCenter and they can start their VM(s) and open the Web Console from the vSphere web interface, but I would prefer to start the VM(s) for them, and open a browser window(s) into the Web Console for the VM(s) so they don’t ever see the vCenter UI.

 

Do you know if it’s possible to start a Web Console session (not a Remote Console) using pyVmomi? Or some other Python library?

 

I appreciate all your help.

 

Regards,

 

Greg

**Comment by prziborowski** [comment]
I've never tried any of that, so I don't have any concrete information.
I notice if I open a web console I end up with a url like: `https://$IP/ui/webconsole.html?vmId=$VMID&vmName=$VMNAME&serverGuid=$VCINSTANCEUUID&locale=en-US`. But that likely only loads up because the browser's cookies have me authenticated. I don't know if it would in your scenario.

You may be able to experiment there.

If that leads to a dead end, another approach is to use [VMware HTML Console SDK](https://code.vmware.com/web/sdk/2.1.0/html-console) which is some javascript that uses websockets to interact with a VM. I think all the handy buttons wouldn't be there and they'd just have something like a VNC window into the VM.
I haven't tried that before (but it seems interesting that I'd like to try myself for other projects of mine).

**Comment by gtomsho** [comment]
Thanks again for your response. I found an example that will produce a URL
for the web console and although it didn't work for vSphere 6.7, I was able
to tweak it to run properly. Appreciate your help.
