### ISSUE TITLE
Property Collector: Getting the folder name of a VM

### ISSUE THREAD

**Issue by jdor300** [vmware/pyvmomi#610]
Hi,
I'm using the property collector to get all of the VMs in the VC's inventory.
I am using the code in the example here: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/vminfo_quick.py

Basically, my FilterSpec is:
ObjectView uses a TraversalSpec for a ContainerView tracking all vim.VirtualMachine instances recrusively starting from the root folder.
There is one PropertySpec  for vim.VirtualMachine

For collecting value types in the VirtualMachine object it works perfectly. But when I try collecting the VM's parent.name  which is the name property of a Folder managed object it throws an InvalidProperty error.

I've tried adding to the selectSet of the ContainerView TraversalSpec, a new TraversalSpec for vim.VirtualMachine with path="parent" and skip=False. Additionally, I've added a PropertySpec for vim.Folder's name property.

This worked but i've got dicts containing the VM properties and after all of the VM dicts, a lot of dicts containing a name of a folder.

What I want is to get the properties of the VM and the name of it's parent folder in a single dict (in a single result)
How can I do that?

Thanks for the helpers :)

**Comment by leroux** [comment]
I had to do something similar to this in the past.

Property collectors took me a bit of time to grasp. Here's how I think how its composed of each of its components:
- `TraversalSpec` defines how to traverse a managed object type to get to other managed object. In other words, it is used to bring more managed objects into the scope of your property collector.
- `ObjectSpec` defines a managed object that you start at.
- `PropertySpec` defines what properties of a managed object to collect (the data you're actually trying to get). It can only collect data from paths that reference a `DataObject` or a field containing a primitive data type. If you reference a path to a `ManagedObject` it will collect its `Managed Object ID (moid)`.

With all that in mind, it seems that you can't have a `PropertySpec` for a `VirtualMachine`  that will go across to a its `parent`, be it `Folder` or `Host`, to collect its name.

The issue is that `PropertyCollector` only provides a normalized view of the data. What you are trying to do is denormalize the data. I ended up having to fetch all the relevant managed objects and then building a denormalized view on top of that.

The approach I took:
- Collect all managed objects and their local properties (including properties linking to another managed object by id)
- Create a mapping from `<managed object type>-<managed object id>` to its local properties.
- Create denormalized view on top of this map.

Here's a rough example illustrating the data transformation:
``
# map built from data returned by PropertyCollector
obj_db = {
    'vim.VirtualMachine:vm-65': {
        'name': 'my cool vm',
        'parent': 'vim.HostSystem:host-99',
    },
   'vim.HostSystem:host-99': {
        'name': 'my host',
  }
}

def denormalize_vm(moid, data):
    return {
        'name': data['name'],
        'host': obj_db[data['parent']]['name'],
   }

vms = filter(lambda k, _: k.startswith('vim.VirtualMachine'), obj_db))
denormalized_vms = map(denormalize_vm, vms)                                            
```

---

Useful things:
```
def jsonify_vsphere_obj(obj):
    """JSONify a vSphere Managed/Data object."""
    class PyVmomiObjectJSONEncoder(json.JSONEncoder):
        """Custom JSON encoder to encode vSphere object."""
        def __init__(self, *args, **kwargs):
            super(PyVmomiObjectJSONEncoder, self).__init__(*args, **kwargs)

        def default(self, obj):  # pylint: disable=method-hidden
            # ISO8601
            if isinstance(obj, datetime.datetime):
                return pyVmomi.Iso8601.ISO8601Format(obj)
            # DataObject
            elif isinstance(obj, pyVmomi.VmomiSupport.DataObject):
                return obj.__dict__
            # ManagedObject
            elif isinstance(obj, pyVmomi.VmomiSupport.ManagedObject):
                # The ManagedObject's reference name.
                return repr(obj)[1:-1]  # strip outer quotes
            # Python Type
            elif isinstance(obj, type):
                return str(obj)
            return json.JSONEncoder.default(self, obj)
    return json.loads(PyVmomiObjectJSONEncoder().encode(obj))
```

**Comment by jdor300** [comment]
Thank you very much :)
