### ISSUE TITLE
Timeout the (smart)connect

### ISSUE THREAD

**Issue by kricd** [vmware/pyvmomi#627]
Hi,
what would be the best way to set a timeout for the connection process? 
If I try to connect to a vcenter that does not exist or answers correct at the moment, the call (*) hangs for about two minutes until it gets an `_[Errno 110] Connection timed out_.`
It seems there is no timeout param for that is there?

(*)
`_si = connect.SmartConnect(host=fqn, user=username, pwd=password)_`

**Comment by kricd** [comment]
Got a solution that works for me for the moment.
I added "timeout" to kwargs in the private method __GetElementTree:
 kwargs = {"context": sslContext, **"timeout": 3**} if sslContext else **{"timeout": 3**}

Should it be something which can be set via the (Smart)Connect parameters?

**Comment by heartleft** [comment]
I have the same problem, how to set time out for the request to vcenter?

**Comment by heartleft** [comment]
OK，the same idea...
i add the `timeout` parameter to class `SoapStubAdapter`:
```python
      self.schemeArgs = {}
```
change to
```python
      self.schemeArgs = {}
      if connectionTimeout:
         self.schemeArgs['timeout'] = connectionTimeout
```
and add `connectionTimeout` parameter to the init method.

**Comment by m451** [comment]
@zpzhoudev 
Notice that you should **not** use `self.schemeArgs['timeout'] = connectionTimeout` since you'll overwrite the `self.schemeArgs` that way and it contains important other settings like cafile or sslcontext, thus: if you do it that way you won't have any of the SSL settings applied that you put into your SoapAdapter. **This breaks the SSL trust**.

Instead use `self.schemeArgs.update({'timeout':connectionTimeout})`. This way the other settings of the variable are kept.


Besides that: this is something that should be fixed a long time ago. A timeout param should be considered normal especially given the fact that the Session connection detection capabilities of the vCenter API are very limited.

**Comment by zpzhoudev** [comment]
@m451 
Hi, your method is good, but actually, they get the same effect.

**Comment by jeking3** [comment]
Related to https://github.com/vmware/pyvmomi/pull/649 ?

**Comment by cloos** [comment]
SmartConnect uses `socket` to create the connection, and socket supports setting a [default timeout](https://docs.python.org/2/library/socket.html?highlight=socket#socket.setdefaulttimeout) in seconds with:

```python
socket.setdefaulttimeout(5)
```
Just set this before calling `SmartConnect.connect` (don't forget to also `import sockets`).

**Comment by m451** [comment]
Thats true if you use SmartConnect. But if you e.g. use SAML as auth method then that's not an option.

**Comment by cloos** [comment]
@m451 which connection method do you mean?

**Comment by m451** [comment]
@cloos I grab a STS token and then use that to get a `vim.ServiceInstance`. You can check an example implementation from VMware e.g. [here](https://github.com/openstack/deb-python-pyvmomi/blob/master/pyVim/sso.py). Thought it's not a standard auth. provider in pyvmomi it's still compatible. But it does bypass the SmartConnect shim.

**Comment by DanielDraganov** [comment]
Since https://github.com/vmware/pyvmomi/releases/tag/v8.0.0.1 `httpConnectionTimeout` was introduced in `SmartConnect`
