### ISSUE TITLE
httplib to requests migration

### ISSUE THREAD

**Issue by hartsock** [vmware/pyvmomi#64]
Migrate from httplib to requests

**Comment by joshk0** [comment]
Is there any particular thing that we have to keep in mind for the conversion?

It seems like as long as InvokeMethod continues to work, there's no reason why the whole HTTPSConnectionWrapper et al. can't just be completely blown away because requests handles it all transparently.

I'd like to take a stab at this too.

**Comment by DanielDraganov** [comment]
Dependency on “requests” is removed 
https://github.com/vmware/pyvmomi/releases/tag/v8.0.0.1

"requests" was introduced in mid-2014 to fix https://github.com/vmware/pyvmomi/issues/13 (No verification of server certificates)
Later the same year, in Python 2.7.9, urllib2 was updated and certificates were getting verified be default. https://peps.python.org/pep-0476/
