### ISSUE TITLE
Remove Distributed Virtual Port Group from Distributed Virtual Switch

### ISSUE THREAD

**Issue by mprahlkamps** [vmware/pyvmomi#704]
I can't seem to find any method to remove a dvpg from a dvs.
Could someone possibly push me in the right direction?

**Comment by moandersson** [comment]
I have the same problem. When i try to use "RemovePortGroup(portgroupName)" I get the following error, even though the user have permission to delete DVS portgroups in vCenter.

`pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Permission to perform this operation was denied.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.HostSystem:host-36',
   privilegeId = 'Host.Config.Network'
}`

Im no VMware guru, but it seem strange to remove the DVS-portgroup from the host instead of doing the operation from the DVS-object, but there is no such method to remove a portgroup just to add? https://github.com/vmware/pyvmomi/blob/master/docs/vim/DistributedVirtualSwitch.rst
Isn't that the whole point with DVS so you don't have to create portgroups on each individual host?

**Comment by moandersson** [comment]
Found it! I could not find it in any documentation but in the code of another library: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_dvs_portgroup.py

So what you need to do is get the dvSwitch and get your dvPortgroup objekt (https://github.com/vmware/pyvmomi/blob/master/docs/vim/dvs/DistributedVirtualPortgroup.rst). Then call the DeleteTask() for that object. Here is a simple example:

```
from pyVim.connect import SmartConnectNoSSL
from pyVmomi import vim

dvs_name = "dvs1"
portgroup_name = "portgroup1"
portgroup = None

vc = SmartConnectNoSSL(host=host, user=username, pwd=password, port=443)
content = vc.RetrieveContent()
container = content.viewManager.CreateContainerView(content.rootFolder, [vim.DistributedVirtualSwitch], True)
for dvs in container.view:
    if dvs.name == dvs_name:
        dv_switch = dvs

portgroups = dv_switch.portgroup
    for pg in portgroups:
        if pg.name == portgroup_name:
            portgroup = pg

task = portgroup.Destroy_Task()
# Task handling not included in example
```
