### ISSUE TITLE
get the snapshot details

### ISSUE THREAD

**Issue by vaidehi8goliwar** [vmware/pyvmomi#751]
i wanted to run the code snapshot_operations.py available in pyvmomi community samples, but in that code we have to pass vm_name as input, i tried to automate it, by taking the arguments through powershell and also i wanted to store the details of snapshot for all the vm's in one run of the code. The issue is when i m collecting the vm names in a list and running it in a loop for assigning each name from list to vm_name variable, it is not fetching the information.

**Comment by pgbidkar** [comment]
Hi @vaidehi8goliwar, Can you try with VM_IDs instead of Names.
in your loop call method (vm = get_obj(content, [vim.VirtualMachine], vm_name)) for each vm name in your list.
get_obj is defined in snapshot_operations.py https://github.com/vmware/pyvmomi-community-samples/blob/9b5b0b4c68dbbfb31f0bb91211308c17fffc1596/samples/snapshot_operations.py#L52

Thanks

**Comment by vaidehi8goliwar** [comment]
Thanks, It's working.
