### ISSUE TITLE
How to get the host kernel version

### ISSUE THREAD

**Issue by kinzun** [vmware/pyvmomi#856]
How to get the host kernel version? Thanks

**Comment by kumahesh** [comment]
I guess you want to know about ESXi host information

`print(service_instance.content.about.osType)
    print(service_instance.content.about.build)
`
It will print ostype as "vmnix-x86" - (For the x86 ESX Server microkernel). Use the same object to get information about build id, release information.. etc.

**Comment by kinzun** [comment]
> I guess you want to know about ESXi host information
> 
> `print(service_instance.content.about.osType) print(service_instance.content.about.build) `
> It will print ostype as "vmnix-x86" - (For the x86 ESX Server microkernel). Use the same object to get information about build id, release information.. etc.

The virtual host can get the kernel ？

**Comment by kumahesh** [comment]
I assume you mean kernel version of guest os. To my knowledge, there are no api's to collect that information from VM. If VM tools are installed, you can run the command "uname" via GuestProcessManager [1]. If it is windows guest, you have to use "systeminfo" instead of "uname".

[1] https://vdc-download.vmware.com/vmwb-repository/dcr-public/723e7f8b-4f21-448b-a830-5f22fd931b01/5a8257bd-7f41-4423-9a73-03307535bd42/doc/vim.vm.guest.ProcessManager.html

**Comment by kinzun** [comment]
@kumahesh Your answer. Very helpful to me. Thank you
