### ISSUE TITLE
retrieve all vm under multi-level nested resource pool using TraversalSpec

### ISSUE THREAD

**Issue by mqliang** [vmware/pyvmomi#903]
Hi, I tried to use the below TraversalSpec to retrieve ALL vm under a resource pool, but it turns out it can only get the top level vms under resource pool:
```
TraversalSpec tSpec_vm = new TraversalSpec();
        tSpec_vm.setName("vmFromResourcePool");
        tSpec_vm.setPath("vm");
        tSpec_vm.setSkip(false);
        tSpec_vm.setType("ResourcePool");
```

 If a resource pool contains multi-level nested resource pools, vms not under the top level resource pool will get ignored. How can I recursively get ALL vms? 

@leroux

**Comment by leroux** [comment]
I'm guessing that since you are trying to get all the VMs under a resource pool, you've specified a single ResourcePool object in your ObjectSpec. Unfortunately, you will have to collect *all* ResourcePool objects (not just the single top-level one) and then perform some post-processing.

Here's a rough idea of how to do this:
1. Define a ContainerView of all ResourcePool.
2. Make an ObjectSpec with that ContainerView as the starting point.
3. Make a PropertySpec for ResourcePool to collect the properties: `vm`, `resourcePool`.

Once you execute that, you'll get a list of ResourcePool which you will need to process somewhat like this:
```python
# pseudocode

# list of ResourcePool managed objects
objects = {
  "resourcePool-1": {
    "vm": [...],
    "resourcePool": ["resourcePool-2", "resourcePool-3"],
  },
  "resourcePool-2": {
    "vm": [...],
    "resourcePool": ["resourcePool-3"],
  },
  "resourcePool-3": {
    "vm": [...],
    "resourcePool": [],
  },
}

def get_vms_recursively(objects, resource_pool_id):
  vms = []
  current_resource_pool = objects[resource_pool_id]

  if current_resource_pool["vm"] == [] and current_resource_pool["resourcePool"] == []:
    return []

  vms.extend(current_resource_pool["vm"])

  for pool_id in current_resource_pool["resourcePool"]:
    vms.extend(get_vms_recursively(objects, poolId))

  return vms  
```

The above code is not the best but hopefully gets the idea across.

**Comment by mqliang** [comment]
@leroux 
> I'm guessing that since you are trying to get all the VMs under a resource pool, you've specified a single ResourcePool object in your ObjectSpec

Oh, sorry for my confusing description. I wanner use TraversalSpec (inventory traversal) to get all VMs. However, my below code dose not get vms recursively.
```
       TraversalSpec tSpec_vm = new TraversalSpec();
        tSpec_vm.setName("vmFromResourcePool");
        tSpec_vm.setPath("vm");
        tSpec_vm.setSkip(false);
        tSpec_vm.setType("ResourcePool");
```

Do you know how to create a TraversalSpec that can recursively traverse vms?

**Comment by leroux** [comment]
To get all VMs, you can use ContainerView of all VirtualMachine. In other words, you should not need to traverse them recursively since vSphere can just tell you what all of them are. [This sample](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/getallvms.py#L98-L101) shows how to make this ContainerView. 

If you need to know the entire chain of resource pools a VM is under, you will need to do something similar as the code in my first comment.

I haven't used pyvmomi or vSphere APis for a few years now so my knowledge may be stale.

**Comment by leroux** [comment]
Maybe you need another TraversalSpec to bring the children resourcePools into scope?

**Comment by mqliang** [comment]
Do you mean:
 
```java
        // TraversalSpec for top level vms under the ResourcePool.
        TraversalSpec tSpec_vm = new TraversalSpec();
        tSpec_vm.setName("vmFromResourcePool");
        tSpec_vm.setPath("vm");
        tSpec_vm.setSkip(false);
        tSpec_vm.setType("ResourcePool");

        // Recurse through the ResourcePool
        TraversalSpec tSpec_resourcePool = new TraversalSpec();
        tSpec_resourcePool.setName("nestedResourcePool");
        tSpec_resourcePool.setPath("resourcePool");
        tSpec_resourcePool.setSkip(false);
        tSpec_resourcePool.setType("ResourcePool");

        // Add both tSpec_vm and tSpec_resourcePool so that it can traverse all vm in nested ResourcePools recursively
        TraversalSpec tSpec_all_vm_recursive = new TraversalSpec();
        tSpec_all_vm_recursive.getSelectSet().add(tSpec_vm);
        tSpec_all_vm_recursive.getSelectSet().add(tSpec_resourcePool);
```

**Comment by leroux** [comment]
Yes, that's what I meant. Is that the solution?

-M



On Thu, Jun 18, 2020, at 13:08, Liang Mingqiang wrote:
> 

> Do you mean:

>         // TraversalSpec for top level vms under the ResourcePool.
        TraversalSpec tSpec_vm = new TraversalSpec();
        tSpec_vm.setName("vmFromResourcePool");
        tSpec_vm.setPath("vm");
        tSpec_vm.setSkip(false);
        tSpec_vm.setType("ResourcePool");

        // Recurse through the ResourcePool
        TraversalSpec tSpec_resourcePool = new TraversalSpec();
        tSpec_resourcePool.setName("nestedResourcePool");
        tSpec_resourcePool.setPath("resourcePool");
        tSpec_resourcePool.setSkip(false);
        tSpec_resourcePool.setType("ResourcePool");

        // Add both tSpec_vm and tSpec_resourcePool so that it can traverse all vm in nested ResourcePools recursively
        TraversalSpec tSpec_all_vm_recursive = new TraversalSpec();
        tSpec_all_vm_recursive.getSelectSet().add(tSpec_vm);
        tSpec_all_vm_recursive.getSelectSet().add(tSpec_resourcePool);

**Comment by mqliang** [comment]
```
2020-06-22 08:13:34.227 +0000 [wdc-08-vc04c01-monitor][1E91AF21E1B2] DEBUG c.v.hdrs.server.vc.VSphereConnector:isConnectionValid - Exception Class : class com.sun.xml.internal.ws.fault.ServerSOAPFaultException Msg : Client received SOAP Fault from server: Permission to perform this operation was denied. Please see the server log to find more detail regarding exact cause of the failure.
```
Looks like extra permission is needed for queries to multi-level RPs. Do you know what  kind of permission is requested, or can you point me to the right person who knows vSphere RABC well?
