### ISSUE TITLE
pyvmomi way slower than govmomi/govc

### ISSUE THREAD

**Issue by karmab** [vmware/pyvmomi#980]
### Describe the bug

The same basic invocation seems to be way slower using python library than go one (at least when leveraging govc)

### Reproduction steps

1. run the following script with time 

```bash
host = 'xxx'
user = 'jimihendrix'
password = 'xxx'

from pyVim import connect
si = connect.SmartConnectNoSSL(host=host, port=443, user=user, pwd=password)
print(si.content.about)
```

2. compare time with 

```bash
export GOVC_URL='xxx'
export GOVC_USERNAME='ericclapton'
export GOVC_PASSWORD='xxx'
export GOVC_INSECURE=1
govc about
```

3. cry since it takes 5 seconds with python script and only one with govc

### Expected behavior

similar time

**Comment by LarsBingBong** [comment]
Any news here?

**Comment by prziborowski** [comment]
It seems like this could be more environment dependent than a problem with pyVmomi itself.
```
$ time python connect.py
...
real	0m0.582s
user	0m0.436s
sys	0m0.044s
```

And if I modify to use Connect rather than SmartConnect
```
$ time python connect.py
(vim.AboutInfo) {
...
real	0m0.490s
user	0m0.375s
sys	0m0.059s
```

I'm guessing if govc is ~1 that the latency between the server is not too bad. I don't know if govc does version negotiation (equivalent to smart connect, or something else).

I can't get python to be faster than ~0.5 seconds as loading all the necessary modules takes that long.

**Comment by larssb** [comment]
Thank you @prziborowski ,

You're suggestions on the linked issue is really insightful and there's a lot of optimization there to reap - that's how I read it.

Thanks - I'll ping @karmab on it.

Again, thank you

**Comment by larssb** [comment]
Should we close this one @karmab ?

**Comment by karmab** [comment]
yeah, lets close
